---
title: "dashboard"
author: "Sarah Gonyo"
date: "2023-04-27"
output: html_document
---

```{r}
library(haven)
library(labelled)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(shiny)
library(shinydashboard)
library(broom)
library(stargazer)
library(shinycssloaders)

###############
# Import data #
###############
data_subset <- read_rds(file = "./data/processed/data_subset.rds")

################
# Prepare data #
################

data_subset <- na.omit(data_subset)

data_subset$male <-
  factor(data_subset$male, labels = c("Female", "Male"))

data_subset$education <-
  factor(data_subset$education, labels = c("Low", "Medium", "High"))

country <- unique(data_subset$country)
country <- append(country, "Overall", after = 0)
```

```{r}
####################
# Create Shiny App #
####################

#Body
body <- dashboardBody(fluidRow(
  box(
    title = "Overview",
    width = 12,
    "The purpose of this app is to understand attitudes towards gender roles and immigration using data from the ",
    tags$a(href = "https://search.gesis.org/research_data/ZA7500#variables%7Cexploredata-ZA7500_Varv80%7C0%7Cvariable_order%7Casc%7Cv80", "European Value Study (EVS)"),
    "from 2017. The EVS is a large-scale, cross-national and longitudinal survey research on how Europeans think about family, work, religion, politics, and society.",
    "The first tab shows graphs exploring the relationship between your selected outcome variable and three controls: age, education, and sex. The second tab shows the coefficients and residuals plot of a regression analysis between y our selected outcome variable and selected control variables",
    "Four inputs are required to use this app. First, select a country from the drop-down menu below. Next, select between two outcome variables. Then, select sex and/or education as your control variables (age is included by default). Finally, select the number of age polynomials you would like to include in the regression (e.g., selecting 3 includes age, age^2, and age^3).",
    selectInput("country", "Select a country", country),
    radioButtons(
      "outcome",
      "Select an outcome variable",
      c("Job Priority" = "job_priority", "Child Suffers" = "child_suffer")
    ),
    checkboxGroupInput(
      "control",
      "Select control(s)",
      c("Education" = "education", "Sex" = "male")
    ),
    numericInput(
      "poly_age",
      "Select age polynomials",
      1,
      min = 1,
      max = 5
    ),
    downloadButton("report", "Generate report")
  )
),
fluidRow(tabBox(
  title = "Results",
  width = 12,
  tabPanel(
    "Exploration",
    withSpinner(plotOutput("outcome_plot"))
  ),
  
  tabPanel(
    "Regression",
    box(
      withSpinner(tableOutput("model")),
      width = 6,
      title = "Model Summary"
    ),
    box(withSpinner(plotOutput("residuals")),
        width = 6,
        title = "Residuals Plot")
  )
)))

#UI
ui <- dashboardPage(
  dashboardHeader(title = "European Value Study"),
  dashboardSidebar(disable = TRUE),
  body
)

#Server
server <- function(input, output, session) {
  data <- reactive(if (input$country == "Overall")
  {
    data_subset
  } else{
    data_subset %>%
      filter(country == input$country)
  })
  
  #########
  # Tab 1 #
  #########
  
  output$outcome_plot <- renderPlot({
    if (input$outcome == "child_suffer") {
      data() %>%
        ggplot(aes(
          x = age,
          y = child_suffer,
          color = as.factor(education)
        )) +
        geom_line(stat = "summary", fun = "mean") +
        labs(color = "Education", x = "Age", y = "When a mother works for pay, the children suffer") +
        facet_wrap( ~ male,
                    ncol = 1,
                    scales = "free_y",
                    labeller = label_value) +
        ggtitle(paste0(input$country, " Results"))
      
    } else{
      data() %>%
        ggplot(aes(
          x = age,
          y = job_priority,
          color = as.factor(education)
        )) +
        geom_line(stat = "summary", fun = "mean") +
        labs(color = "Education", x = "Age", y = "Employment priority to nationals over immigrants") +
        facet_wrap( ~ male,
                    ncol = 1,
                    scales = "free_y",
                    labeller = label_value) +
        ggtitle(paste0(input$country, " Results"))
    }
  })
  
  
  
  #########
  # Tab 2 #
  #########
  
  #    variables <- reactive({
  #     if (is.null(input$control)) {
  #       return(NULL)
  #     }
  #      if("education" %in% input$control){
  #        if("male" %>% input$control){
  #          c("education","male")
  #        }else{
  #          c("education")
  #        }
  #      }else{
  #        c("male")
  #      }
  # })
  
  f <- reactive({
    if (is.null(input$control)) {
        input$outcome ~ poly(age, input$poly_age)
    }
    if ("education" %in% input$control) {
      if ("male" %>% input$control) {
        input$outcome ~ education + male + poly(age, input$poly_age)
      } else {
        input$outcome ~ education + poly(age, input$poly_age)
      }
    } else {
      input$outcome ~ male + poly(age, input$poly_age)
    }
  })
  
     model <- reactive({
       lm(f(), data = data())
     })
  
  # output$model <- renderDataTable({
  #   print(tidy(model()))
  #   })
  
  output$residuals <- renderPlot({
    ggplot(model(), aes(x = .fitted, y = .resid)) +
      geom_point() +
      geom_hline(yintercept = 0) +
      labs(x = "Residuals", y = "Predicted") +
      ggtitle(paste0(input$country, " Predicted vs Residuals Plot"))
  })
  
  ###################
  # Download Report #
  ###################
  
  output$report <- downloadHandler(
    filename = "dynamic_report.html",
    content = function(file) {

      tempReport <- file.path(tempdir(), "dynamic_report.Rmd")
      file.copy("dynamic_report.Rmd", tempReport, overwrite = TRUE)
      
      # Set up parameters to pass to Rmd document
      params <-
        list(
          country = input$country,
          outcome = input$outcome,
          control = input$control,
          age = input$poly_age
        )
      
      # Knit the document, passing in the `params` list, and evaluate
      rmarkdown::render(
        tempReport,
        output_file = file,
        params = params,
        envir = new.env(parent = globalenv())
      )
    }
  )
}

shinyApp(ui, server)

```
